### ISSUE TITLE
Can we put this into a Cocoapod?

### ISSUE THREAD

**Issue by jpotts18** [Haneke/HanekeSwift#114]

**Comment by joanromano** [comment]
Today I was trying to take advantage of the new pre version of Cocoapods and submit the public podspec to the repo, so that we can merge the podspec branch to master here. 

However, I am getting a `error: no such module 'UIKit'` when I first attempt to lint the podspec. While I am trying to solve this any help would be appreciated. I believe we should be able to do this since Alamofire has his own public podspec already https://github.com/CocoaPods/Specs/tree/master/Specs/Alamofire/1.1.3

**Comment by mikenolimits** [comment]
http://prntscr.com/5xu5cl :(

**Comment by mikenolimits** [comment]
It seems I had to import HanekeSwift instead of Haneke, and it worked like a charm :)

**Comment by joanromano** [comment]
@mikenolimits but you are trying it with the branch `podspec` as suggested above right?

**Comment by mikenolimits** [comment]
@joanromano correct.

**Comment by arnaudmeunier** [comment]
Branch podspec works great for me. Merge to Master?

**Comment by joanromano** [comment]
@arnaudmeunier I'd first have to create the public podspec for that. I'll try it again asap

**Comment by arnaudmeunier** [comment]
Awesome. Thanks :)

**Comment by oziade** [comment]
I tried with the given branch to use Haneke with Cocoapods.
But i got an error when i try to set an image from an URL in a UITableViewCell (hnk_setImageFromURL) :
"Cancelled set image for " ....
The message is sent by the hnk_shouldCancelForKey function because the hnk_fetcher?.key is nil.

It works fine if i just copy the xcodeproj file in my project, as described in the installation guide, instead of using Cocoapods.
Any idea about this ?

Thanks

**Comment by AllenConquest** [comment]
How do I use HanekeSwift in Xcode 6.3 (Swift 1.2), as the podspec branch doesn't seem to be Swift 1.2 compatible?

**Comment by shivateja** [comment]
Why isn't this merged to master yet?

**Comment by hpique** [comment]
Merged into master but not pushed to Cocoapods trunk due to a name conflict with Haneke Objective-C. For now, use:

```ruby
use_frameworks!
pod 'Haneke', :git => 'https://github.com/Haneke/HanekeSwift.git'
```

**Comment by hpique** [comment]
See #174 for more details, or if you know how to fix this.
