### ISSUE TITLE
Is there a Tutorial other than the one here?

### ISSUE THREAD

**Issue by hcri50** [Haneke/HanekeSwift#133]
I am not having any success.
Can someone point me to a Tutorial Please

**Comment by glenselle** [comment]
@hcri50 The README is pretty clear and your question is very vague. I'd suggest you either ask your question over on StackOverflow and provide as much detail as possible. Or, if you think there's an actual issue with Haneke, describe it in more detail. Opening issues for trivial reasons like "it's not working" doesn't help you (since nobody knows what your problem is) and just adds more work for maintainers of Haneke to close issues like this.

**Comment by hpique** [comment]
I agree with @glenselle but I also recognize that both this version of Haneke and the Swift community at large are new enough to be a bit more lenient than with other projects. @hcri50, if you feel like articulating with detail what you tried and what you failed to achieve we might be able to help you. In the meantime, I'm closing this.
