### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by shmakovigor** [Haneke/HanekeSwift#202]
Do you plan to update project for Swift 2.0?

**Comment by FarajiMehrdad** [comment]
Ya, I'm waiting for update!

**Comment by meteochu** [comment]
I did some very quick migration to Swift 2.0 that you guys can use in the mean time. (Mostly just getting rid of errors and rewriting parts of the Error Handling. Note that it's updated "to work" and not really optimized, etc) 
https://github.com/meteochu/HanekeSwift/tree/swift-2.0

**Comment by shmakovigor** [comment]
thanks!

**Comment by FarajiMehrdad** [comment]
thank you for updating.

**Comment by caldofran** [comment]
Waiting for Swift 2 support guys

**Comment by anthonycastelli** [comment]
I second this one!

**Comment by clementprem** [comment]
Thanks @meteochu meteochu. Waiting for the official Swift 2 update

**Comment by keith** [comment]
Many projects maintain a swift-2.0 branch before the official release just to make it easier for people trying to transition. Looks like @meteochu's is a good start

**Comment by dcunited001** [comment]
i was using the swift 2.0 branch a few days ago.  i couldn't get the callbacks to work from within UICollectionView collectionView(collectionView, cellForItemAtIndexPath) method.  i kept getting wierd mallocs and pointer errors.  

The problem is that I tried switching to Haneke obj-c and couldn't get that to work.  So i switched back to the Swift 2.0 branch and now the caching is completely broken and I can't use Haneke at all.  I tried resetting the simulators.  Nothing works.  It fails everytime it loads an image.  Not sure whether this is a swift-2.0 branch problem, a Haneke problem or a problem with my own environment.

**Comment by bradycoye** [comment]
@dcunited001 this branch still works fine in my project. Must be an environment issue

**Comment by dcunited001** [comment]
@bradycoye @meteochu i added a [Haneke branch](https://github.com/appistack/appistack-swift/tree/haneke) specifically for the issues I'm experiencing.  I've set up the app to use an online API in development, so you should be able to login temporarily with `appistack at gmail` and `PassWord!`

I'm getting wierd issues when trying to use hnk_setImageFromURL() with a callback, but only from within a collectionView.  In particular, inside the `UICollectionView collectionView(collectionView, cellForItemAtIndexPath)` method for my collectionView.   I'm unsure of whether these issues are specific to Swift 2.0, but that's what I'm using.

**Comment by dcunited001** [comment]
ok well now there is no problem because `appistack-rails.herokuapp.com` no longer has any rows in the `artists` or `sounds` tables.... lol really not sure how that happened, but it did literally 20 minutes ago.  jeez

**Comment by dcunited001** [comment]
instead of using `self.collectionView.reloadItemsAtIndexPaths([indexPath])` to reload specific cells inside the Hanake callback, i tried calling `invalidateLayout()` and this works.  i think `reloadItemsAtIndexPaths` was blowing up because it was causing too much to happen at once.  maybe bc each call was allocating new threads or something.  

`invalidateLayout()` seems like it would be more appropriate, especially if working with more images, since multiple calls would trigger the behavior a limited number of times.

```swift
        cell.imgView.hnk_setImageFromURL(artist.headshotUrl(), success: { (img) in
            //i just want to trigger the cell to resize once the image is downloaded
            cell.imgView.image = img
            UIView.animateWithDuration(0.3, animations: { self.collectionView.collectionViewLayout.invalidateLayout() })
        })
```

also, some of the errors were being caused by attempting to print within hanake callback when it was within the collection view.  so that was making it harder to troubleshoot.

**Comment by keith** [comment]
Here's the PR for swift 2 support https://github.com/Haneke/HanekeSwift/pull/221

**Comment by githotto** [comment]
Is there a working Swift 2 version; I'm trying to use it in Xcode 7 (7A220) but am getting quite a lot of errors, which I can't seem to fix yet.

**Comment by yurrriq** [comment]
@githotto, see [mobinzk's comment][1] on #222.

[1]: https://github.com/Haneke/HanekeSwift/issues/222#issuecomment-141474067

**Comment by githotto** [comment]
Hi Eric,
Thanks for the quick response.
It worked like a charm, thanks again, you saved my day!

By the way: before I read your email I had a compile-error free working
version with Maplebacon (see: https://github.com/zalando/MapleBacon) but
this didn't render all Images correctly (or at all) in a UITableView.
So I was very happy to read your suggestion, causing me to switch back to
Haneke with a working app now.
Great, thanks again, have a nice weekend.

Kind regards,
Otto van Verseveld

2015-09-19 1:34 GMT+02:00 Eric Bailey <notifications@github.com>:

**Comment by yurrriq** [comment]
Great! I'm glad I could help.

**Comment by hpique** [comment]
Swift 2.0 support is now on master. Thanks to @meteochu for providing an alternative while this was unavailable.
