### ISSUE TITLE
remove image from all FormatName 

### ISSUE THREAD

**Issue by schmichri** [Haneke/HanekeSwift#273]
Hey, 
when I set an image to an UIImageView (scaled) with the hnk_setImageFromUrl extension function, how can I remove this again from the Cache. 
I've tried: 
 `profileImageView.hnk_setImageFromURL(NSURL(string: imageUrl)!)`
` Shared.imageCache.remove(key: imageUrl!)`

checking the FileSystem and reading the code it's only removes images from `HanekeGlobals.Cache.OriginalFormatName`
which still leads to cached images in the `Auto*aspectfill caches `

`shared-images/auto-160.0x160.0-aspectfill:`
`-rw-r--r--  1 chris  staff  123123  9 Jan 13:26 https%3A%2F%2Fapi.example.com%2Fpubapi%2Fusers%2Fchris%2Fpicture``

Is this expected behavior?

Best Chris 
PS Thanks for your great work ;)

**Comment by hpique** [comment]
Thanks @schmichri! 

You can do: 

`Shared.imageCache.remove(key: imageUrl, format: profileImageView.hnk_format.name)`

Still, I think we probably should have a `removeFromAll` method.

**Comment by schmichri** [comment]
OK this works. Thank. 

Just for completeness:
`Shared.imageCache.remove(key: imageUrl, formatName: profileImageView.hnk_format.name)`

**Comment by hpique** [comment]
Edited. Thanks!

**Comment by gecoool** [comment]
Hey there. I had the same problem as this one. I've tried a couple of combinations, removing all cache, disk image for key, etc, but in the end I have realized that my problem was in the NSURLSession, because that was the default session (so my image was cached by the OS), using the default requestCachePolicy. I am posting my solution here in the event that someone would have to refresh an image using the same URL (but with the content changed). I know it sounds odd, but working with third party API has brought me into this situation. 

@implementation HNKNetworkFetcher(Subclassing)

- (NSURLSession*)URLSession
{
    NSURLSessionConfiguration *myConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
    myConfiguration.requestCachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
    
    return [NSURLSession sessionWithConfiguration:myConfiguration];
    //    return [NSURLSession sharedSession];
}

@end
