### ISSUE TITLE
Placeholder image not replaced when downloading is interrupted.

### ISSUE THREAD

**Issue by hifall** [Haneke/HanekeSwift#336]
I am using Haneke to download image for an image view in a table cell. And I am seeing this issue where the placeholder image is not replaced. To reproduce this issue, I did:

1 add a table cell with an image view whose image is managed by Haneke, i.e., imageView?.hnk_setImageFromURL(...); a placeholder image is passed in while calling hnk_setImageFromURL. Now the cell appears with the placeholder image;
2 take the app to the background, so that the downloading is interrupted;
3 after a while (maybe ~1 minute), take the app to the foreground;
4 the placeholder is never replaced if I do nothing;
5 if I tap the placeholder image to switch to fullscreen, it can show the "real" image after a while; but then if I tap it again to quite fullscreen, the table cell still shows the placeholder image, rather than the "real" image.

My question is: how to replace the placeholder image once the real image is downloaded, if the downloading has been interrupted like described above?

Thanks!

**Comment by joe528** [comment]
You take the app to the background and you know the downloading is interrupted. And after the app is back to the foreground, the downloading of the actual image is considered failed. So I think what you observe is totally reasonable (by design).

I also had this test case for my app and my solution is to call `hnk_setImageFromURL` again for each visible images in my table view when the app is taken back to the foreground (in app becoming active event).
